### ISSUE TITLE
Game crashes when trying to break

### ISSUE THREAD

**Issue by EnderRobber101** [bunnyi116/fabric-bedrock-miner#28]
Description: Unexpected error

java.lang.NoSuchFieldError: Class net.minecraft.class_1893 does not have member field 'net.minecraft.class_1887 field_9131'
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.getBlockBreakingSpeed(InventoryManagerUtils.java:159)
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.isInstantBreakingBlock(InventoryManagerUtils.java:127)
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.canInstantlyMinePiston(InventoryManagerUtils.java:110)
	at yan.lx.bedrockminer.task.TaskManager.reverseCheckInventoryItemConditionsAllow(TaskManager.java:165)
	at yan.lx.bedrockminer.task.TaskManager.addTask(TaskManager.java:51)
	at net.minecraft.class_310.handler$zzc000$bedrockminer$handleBlockBreaking(class_310.java:3701)
	at net.minecraft.class_310.method_1590(class_310.java:1741)
	at net.minecraft.class_310.method_1508(class_310.java:2122)
	at net.minecraft.class_310.method_1574(class_310.java:1938)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by bunnyi116** [comment]
Which version of Minecraft and mod do you use?

**Comment by EnderRobber101** [comment]
Version: 1.21
Mods: 
Wurst-Client-v7.43.1-MC1.21.jar
XaerosWorldMap_1.38.8_Fabric_1.21.jar
Xaeros_Minimap_24.2.1_Fabric_1.21.jar
bedrock-miner-1.20.6-1.2.21.jar
entityculling-fabric-1.6.6-mc1.21.jar
fabric-api-0.100.1+1.21.jar
iris-1.7.1+mc1.21.jar
litematica-fabric-1.21-0.18.999-sakura.2.jar
lithium-fabric-mc1.21-0.12.6.jar
malilib-fabric-1.21-0.19.999-sakura.1.jar
minihud-fabric-1.21-0.31.999-sakura.2.jar
modmenu-11.0.0-rc.2.jar
sodium-fabric-0.5.9+mc1.21.jar
tweakeroo-fabric-1.21-0.20.999-sakura.2.jar
Mods zip
[mods.zip](https://github.com/user-attachments/files/15934061/mods.zip)

**Comment by EnderRobber101** [comment]
Update: I removed all mods(except fabric api) and it still crashes

**Comment by bunnyi116** [comment]
You should use the latest version of mod instead of 1.20.6 'bedrock-miner-1.20.6-1.2.21.jar' ，You should use version 1.21.1.

**Comment by EnderRobber101** [comment]
Didn't notice. Thanks
